baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "RS Bot Spot"
theme = "hyde"

[Params]
  dateFormat = "January 2, 2006"
  description = "Making Runescape botting & gold-farming easier."

# HTTP2
[outputs]
home = [ "HTML", "RSS", "REDIR", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

#
