baseURL = "https://rsbotspot.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "RS Bot Spot"
theme = "hyde"
canonifyURLs = true

[Params]
  dateFormat = "January 2, 2006"
  description = "Making Runescape botting & gold-farming easier."
